### ISSUE TITLE
socks5代理不好使，http得代理可以使用

### ISSUE THREAD

**Issue by Zxc123456zxc** [pingc0y/go_proxy_pool#10]
socks5代理不好使，使用报错，http得代理可以使用
![image](https://user-images.githubusercontent.com/63491799/229699757-b6f4c470-cb0f-4b46-82ca-9fb783080dcc.png)
![image](https://user-images.githubusercontent.com/63491799/229699907-175f02dd-65b2-4585-a900-02450373778d.png)

**Comment by pingc0y** [comment]
可以看到使用代理: 是空的，说明当前代理池里没有socket5的代理，可以访问首页查看下socket5代理数量

**Comment by Zxc123456zxc** [comment]
好的
