### ISSUE TITLE
Linux的执行不了

### ISSUE THREAD

**Issue by ketchup1995** [pingc0y/go_proxy_pool#2]
大佬你好，给权限了还不行，有什么限制吗
![image](https://user-images.githubusercontent.com/87350553/203252046-3bdd7e79-5b28-4311-826b-60f9456c3f98.png)

**Comment by pingc0y** [comment]
太狗血了，在ide默认终端里跑的命令没生效，生成的全是windwos的，我重新打包生成下

**Comment by pingc0y** [comment]
已经重新上传，师傅可以下载试试

**Comment by ketchup1995** [comment]
> 已经重新上传，师傅可以下载试试

![image](https://user-images.githubusercontent.com/87350553/203450255-90cb8318-4449-491b-96e4-aeabfc204955.png)
还是不行呢师傅

**Comment by pingc0y** [comment]
注意下是不是跑的之前的了，我也是centos环境，
![image](https://user-images.githubusercontent.com/106963235/203451848-72b84746-bd88-464a-b54e-cf484087833d.png)

**Comment by ketchup1995** [comment]
> 注意下是不是跑的之前的了，我也是centos环境， ![image](https://user-images.githubusercontent.com/106963235/203451848-72b84746-bd88-464a-b54e-cf484087833d.png)

可以了，谢谢师傅
