### ISSUE TITLE
大佬，SOCKET5无法使用是什么原因

### ISSUE THREAD

**Issue by ketchup1995** [pingc0y/go_proxy_pool#4]
![image](https://user-images.githubusercontent.com/87350553/203727478-d5bfa6e4-34e9-4c1d-a4cf-82fefebceeae.png)

**Comment by pingc0y** [comment]
有没有可能是，你代理池里没有SOCKET5的代理

**Comment by pingc0y** [comment]
自己扩展一些socket5的代理源吧
